string city;
System.debug('city = ' + city);

string country = '';
System.debug('country = ' + country);

string region = 'America';
System.debug('America');
System.debug('region = ' +region);

integer sayi1 = 50;
System.debug('sayi1 = ' + sayi1);

Integer sayi2 = sayi1/2;
System.debug('sayi2 = ' + sayi2);

Boolean isActive = true;
System.debug('isActive = ' + isActive);

Boolean cond1 = 7>3;
System.debug('cond1 = ' + cond1);

Boolean cond2 = 11>35;
System.debug('cond2 = ' + cond2);