public class denemeclass {
    public void method1(){
        system.debug('Merhaba Dunya');
     

    }
    public void method2(Integer x,Integer y){
        Integer sum = x + y;

        system.debug('Sum : '+sum);
        
    }
    public void method3(string fullname , Integer age){
        
        system.debug('Full Name: '+fullname);
        system.debug('Age : '+age);
        
        
    }
}

