public class CheckDatatypes {
    public void methodBoolean() {
        boolean checkBoolean = null;
        system.debug(checkBoolean);
    }
    public void methodInteger(){
        integer varfirst = 1;
        integer varsecond = 2;
        system.debug(varfirst);
        system.debug(varsecond);
    }
    public void stringMethod(){
        string varname='Name';
        string var2name='Elif';
        system.debug(varname);
        system.debug(var2name);
    }
    public void methodId(){
        id checkId = '0010900001wBZ90AAG';
        system.debug(checkId);
    }
    public void methodDouble(){
        Double varfirst=1.23;
        Double varsecond=209.764;
        system.debug(varfirst);
        system.debug(varsecond);
    }
}
